import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcrypt';

const prisma = new PrismaClient();

async function main(): Promise<void> {
  console.log('🌱 Seeding Gamratic database...');

  // Create seed users
  const passwordHash = await bcrypt.hash('Password123!', 12);

  const users = await Promise.all([
    prisma.user.create({ data: { username: 'NightOwl', email: 'nightowl@gamratic.dev', passwordHash, bio: 'Hardcore RPG enthusiast. 3000+ hours in FromSoft games.' } }),
    prisma.user.create({ data: { username: 'PixelKnight', email: 'pixelknight@gamratic.dev', passwordHash, bio: 'Indie game advocate and metroidvania addict.' } }),
    prisma.user.create({ data: { username: 'CriticalMass', email: 'criticalmass@gamratic.dev', passwordHash, bio: 'Strategy gamer and narrative connoisseur.' } }),
    prisma.user.create({ data: { username: 'GhostFrame', email: 'ghostframe@gamratic.dev', passwordHash, bio: "Speedrunner. If it has a timer, I'm racing." } }),
    prisma.user.create({ data: { username: 'VoidWalker', email: 'voidwalker@gamratic.dev', passwordHash, bio: 'Roguelike diehard with a soft spot for pixel art.' } }),
  ]);

  // Game data
  const gamesData = [
    {
      title: 'Elden Ring',
      genres: JSON.stringify(['RPG', 'Action']),
      platforms: JSON.stringify(['PC', 'PS5', 'Xbox Series X']),
      releaseYear: 2022,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1245620/header.jpg',
      coverGradient: 'linear-gradient(135deg, #1a1a2e 0%, #2d1b3d 30%, #c9a227 100%)',
      accentColor: '#c9a227',
      criticScore: 96,
      description: 'A vast open-world RPG crafted by Hidetaka Miyazaki and George R.R. Martin.',
      longDescription: 'Elden Ring is an action RPG set in the Lands Between, a vast and sprawling open world teeming with danger and discovery. Crafted by the legendary collaboration of FromSoftware\'s Hidetaka Miyazaki and fantasy novelist George R.R. Martin, the game features punishing combat, deep lore, and an unprecedented sense of freedom. Explore six major regions, face towering demigod bosses, and uncover the mystery of the shattered Elden Ring.',
      developer: 'FromSoftware',
      publisher: 'Bandai Namco',
      tags: JSON.stringify(['Open World', 'Souls-like', 'Fantasy', 'Co-op', 'Dark Fantasy']),
    },
    {
      title: 'Cyberpunk 2077',
      genres: JSON.stringify(['RPG', 'Action']),
      platforms: JSON.stringify(['PC', 'PS5', 'Xbox Series X']),
      releaseYear: 2020,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1091500/header.jpg',
      coverGradient: 'linear-gradient(135deg, #0a0a1a 0%, #1a0a2e 40%, #ff3366 100%)',
      accentColor: '#ff3366',
      criticScore: 86,
      description: 'An open-world action-adventure RPG set in the megalopolis of Night City.',
      longDescription: 'Cyberpunk 2077 is an open-world RPG set in Night City, a megalopolis obsessed with power, glamour, and body modification. You play as V, a mercenary outlaw going after a one-of-a-kind implant that is the key to immortality. Featuring deep character customization, branching narratives, and a stunning neon-drenched world, the game delivers a mature, thought-provoking experience in a dystopian future.',
      developer: 'CD Projekt Red',
      publisher: 'CD Projekt',
      tags: JSON.stringify(['Cyberpunk', 'Open World', 'FPS', 'Story Rich', 'Mature']),
    },
    {
      title: 'Hollow Knight',
      genres: JSON.stringify(['Metroidvania', 'Action']),
      platforms: JSON.stringify(['PC', 'PS4', 'Xbox One', 'Nintendo Switch']),
      releaseYear: 2017,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/367520/header.jpg',
      coverGradient: 'linear-gradient(135deg, #0a0e1a 0%, #1a2a3e 50%, #4a9ead 100%)',
      accentColor: '#4a9ead',
      criticScore: 90,
      description: 'A beautifully hand-drawn 2D action-adventure through a vast ruined kingdom.',
      longDescription: 'Hollow Knight is a classically styled 2D action-adventure across a vast interconnected world. Explore twisting caverns, ancient cities, and deadly wastelands. Battle tainted creatures and befriend bizarre bugs. The game features tight, satisfying combat, gorgeous hand-drawn art, over 130 enemies, 30+ bosses, and a hauntingly beautiful soundtrack that brings the world of Hallownest to life.',
      developer: 'Team Cherry',
      publisher: 'Team Cherry',
      tags: JSON.stringify(['Metroidvania', 'Indie', 'Atmospheric', 'Difficult', '2D']),
    },
    {
      title: 'Hades',
      genres: JSON.stringify(['Roguelike', 'Action']),
      platforms: JSON.stringify(['PC', 'PS5', 'Xbox Series X', 'Nintendo Switch']),
      releaseYear: 2020,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1145360/header.jpg',
      coverGradient: 'linear-gradient(135deg, #1a0a0a 0%, #3d1a1a 40%, #ff6b35 100%)',
      accentColor: '#ff6b35',
      criticScore: 93,
      description: 'Defy the god of the dead as you battle out of the Underworld in this rogue-like.',
      longDescription: 'Hades is a god-like rogue-like dungeon crawler that combines the best aspects of Supergiant\'s critically acclaimed titles. As the immortal Prince of the Underworld, you\'ll wield the powers and mythic weapons of Olympus to break free from the clutches of the god of the dead himself. Each run is unique with procedurally generated encounters, unlockable weapons, and an ever-evolving story told through incredible voice acting and character interactions.',
      developer: 'Supergiant Games',
      publisher: 'Supergiant Games',
      tags: JSON.stringify(['Roguelike', 'Indie', 'Action', 'Greek Mythology', 'Story Rich']),
    },
    {
      title: 'God of War',
      genres: JSON.stringify(['Action', 'Adventure']),
      platforms: JSON.stringify(['PC', 'PS4', 'PS5']),
      releaseYear: 2018,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1593500/header.jpg',
      coverGradient: 'linear-gradient(135deg, #0a0a1a 0%, #1a1a3e 40%, #2196f3 100%)',
      accentColor: '#2196f3',
      criticScore: 94,
      description: 'Kratos and his son Atreus embark on a journey through Norse mythology.',
      longDescription: 'God of War takes Kratos to the realm of Norse gods and monsters. As a father teaching his son about the world, Kratos must master the rage that has long defined him. Together with Atreus, players journey through breathtaking landscapes, encounter Norse mythology\'s most fearsome creatures, and uncover the truth of their divine heritage. The game reinvents the series with an over-the-shoulder free camera and a deeply emotional narrative.',
      developer: 'Santa Monica Studio',
      publisher: 'Sony Interactive',
      tags: JSON.stringify(['Mythology', 'Hack and Slash', 'Story Rich', 'Cinematic', 'Singleplayer']),
    },
    {
      title: 'Red Dead Redemption 2',
      genres: JSON.stringify(['Action', 'Adventure']),
      platforms: JSON.stringify(['PC', 'PS4', 'Xbox One']),
      releaseYear: 2018,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1174180/header.jpg',
      coverGradient: 'linear-gradient(135deg, #1a0e05 0%, #3d2010 40%, #b85c1e 100%)',
      accentColor: '#b85c1e',
      criticScore: 97,
      description: 'An epic tale of life in America\'s unforgiving heartland.',
      longDescription: 'Red Dead Redemption 2 is Rockstar Games\' sprawling epic about life in America at the dawn of the modern age. Arthur Morgan and the Van der Linde gang are on the run across America as the era of the Wild West draws to a close. With federal agents and bounty hunters closing in, the gang must rob, steal, and fight their way across the rugged heartland to survive. An unparalleled achievement in open-world storytelling with breathtaking environmental detail.',
      developer: 'Rockstar Games',
      publisher: 'Rockstar Games',
      tags: JSON.stringify(['Open World', 'Western', 'Story Rich', 'Realistic', 'Multiplayer']),
    },
    {
      title: "Baldur's Gate 3",
      genres: JSON.stringify(['RPG', 'Strategy']),
      platforms: JSON.stringify(['PC', 'PS5', 'Xbox Series X']),
      releaseYear: 2023,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1086940/header.jpg',
      coverGradient: 'linear-gradient(135deg, #0a0a1a 0%, #2a1040 40%, #9b59b6 100%)',
      accentColor: '#9b59b6',
      criticScore: 96,
      description: 'A sprawling RPG based on Dungeons & Dragons, featuring turn-based combat.',
      longDescription: "Baldur's Gate 3 is a story-rich, party-based RPG set in the universe of Dungeons & Dragons. Choose from 12 classes and 11 races, or play as an Origin hero with a hand-crafted background. Adventure, loot, battle, and romance your way through the Forgotten Realms and beyond. With unprecedented freedom of choice and consequences that ripple throughout the story, Larian Studios delivers one of the greatest RPGs ever created.",
      developer: 'Larian Studios',
      publisher: 'Larian Studios',
      tags: JSON.stringify(['CRPG', 'Turn-Based', 'Co-op', 'D&D', 'Story Rich']),
    },
    {
      title: 'Disco Elysium',
      genres: JSON.stringify(['RPG', 'Adventure']),
      platforms: JSON.stringify(['PC', 'PS5', 'Xbox Series X', 'Nintendo Switch']),
      releaseYear: 2019,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/632470/header.jpg',
      coverGradient: 'linear-gradient(135deg, #0a1a1a 0%, #1a3a2a 40%, #27ae60 100%)',
      accentColor: '#27ae60',
      criticScore: 91,
      description: 'A groundbreaking RPG where you are a detective with a unique skill system.',
      longDescription: 'Disco Elysium is a groundbreaking open-world RPG. You\'re a detective with a unique skill system at your disposal and a whole city block to carve your path across. Interrogate unforgettable characters, crack murders, or take bribes. Become a hero or an absolute disaster of a human being. The game features no combat — instead, it\'s all dialogue, thought, and consequence. One of the most innovative and literary RPGs ever created.',
      developer: 'ZA/UM',
      publisher: 'ZA/UM',
      tags: JSON.stringify(['Detective', 'Narrative', 'Choices Matter', 'Indie', 'Political']),
    },
    {
      title: 'Dead Cells',
      genres: JSON.stringify(['Roguelike', 'Metroidvania']),
      platforms: JSON.stringify(['PC', 'PS4', 'Xbox One', 'Nintendo Switch']),
      releaseYear: 2018,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/588650/header.jpg',
      coverGradient: 'linear-gradient(135deg, #0a0a2e 0%, #1a1a4e 40%, #e74c3c 100%)',
      accentColor: '#e74c3c',
      criticScore: 89,
      description: 'A roguevania that combines roguelike replayability with metroidvania exploration.',
      longDescription: 'Dead Cells is a roguevania, a 2D action-platformer that combines the best aspects of roguelikes and metroidvanias. Players explore an ever-changing castle with no checkpoints, using a growing arsenal of weapons, skills, and mutations. With tight, responsive controls, gorgeous pixel art, and a non-linear progression system, every run feels fresh and rewarding. The game has been continuously updated with new content packs since its release.',
      developer: 'Motion Twin',
      publisher: 'Motion Twin',
      tags: JSON.stringify(['Roguelike', 'Pixel Art', 'Challenging', 'Fast-Paced', 'Indie']),
    },
    {
      title: 'Into the Breach',
      genres: JSON.stringify(['Strategy', 'Roguelike']),
      platforms: JSON.stringify(['PC', 'Nintendo Switch']),
      releaseYear: 2018,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/590380/header.jpg',
      coverGradient: 'linear-gradient(135deg, #0a1a2e 0%, #1a3050 40%, #3498db 100%)',
      accentColor: '#3498db',
      criticScore: 90,
      description: 'Control powerful mechs to defend civilization from an alien threat in turn-based combat.',
      longDescription: 'Into the Breach is a turn-based strategy game from the creators of FTL. The remnants of human civilization are threatened by gigantic creatures breeding beneath the earth. Control powerful mechs from the future to hold off this alien threat. Each attempt to save the world presents a new randomly generated challenge in this turn-based strategy game. Perfect information means every failure is your own — a chess-like puzzle wrapped in mech warfare.',
      developer: 'Subset Games',
      publisher: 'Subset Games',
      tags: JSON.stringify(['Turn-Based', 'Tactics', 'Indie', 'Minimalist', 'Puzzle']),
    },
    // ── 40 additional games ──────────────────────────────────────
    {
      title: 'The Witcher 3: Wild Hunt',
      genres: JSON.stringify(['RPG', 'Action']),
      platforms: JSON.stringify(['PC', 'PS5', 'Xbox Series X', 'Nintendo Switch']),
      releaseYear: 2015,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/292030/header.jpg',
      coverGradient: 'linear-gradient(135deg, #0a0a1a 0%, #1a2a1a 40%, #5a8a3a 100%)',
      accentColor: '#5a8a3a',
      criticScore: 93,
      description: 'A story-driven open world RPG set in a visually stunning fantasy universe.',
      longDescription: 'The Witcher 3: Wild Hunt is an open-world RPG following Geralt of Rivia, a monster hunter searching for his missing adopted daughter. Set in a war-torn world threatened by the Wild Hunt, the game offers over 100 hours of content, including two massive expansions. Praised for its writing, characters, and world design, it remains one of the greatest RPGs ever made.',
      developer: 'CD Projekt Red',
      publisher: 'CD Projekt',
      tags: JSON.stringify(['Open World', 'Fantasy', 'Story Rich', 'Choices Matter', 'Dark Fantasy']),
    },
    {
      title: 'Dark Souls III',
      genres: JSON.stringify(['RPG', 'Action']),
      platforms: JSON.stringify(['PC', 'PS4', 'Xbox One']),
      releaseYear: 2016,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/374320/header.jpg',
      coverGradient: 'linear-gradient(135deg, #0a0a0a 0%, #1a1a2e 40%, #6a4a2e 100%)',
      accentColor: '#c47a3a',
      criticScore: 89,
      description: 'The final entry in the Dark Souls trilogy, featuring interconnected worlds and punishing combat.',
      longDescription: 'Dark Souls III is the final chapter in the celebrated Dark Souls series. Players traverse sprawling, interconnected environments filled with grotesque enemies, hidden secrets, and devastating boss encounters. The faster-paced combat draws from Bloodborne while retaining the methodical strategy the series is known for.',
      developer: 'FromSoftware',
      publisher: 'Bandai Namco',
      tags: JSON.stringify(['Souls-like', 'Dark Fantasy', 'Difficult', 'Co-op', 'Atmospheric']),
    },
    {
      title: 'Sekiro: Shadows Die Twice',
      genres: JSON.stringify(['Action', 'Adventure']),
      platforms: JSON.stringify(['PC', 'PS4', 'Xbox One']),
      releaseYear: 2019,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/814380/header.jpg',
      coverGradient: 'linear-gradient(135deg, #0a0a1a 0%, #2a1a0a 40%, #d4661e 100%)',
      accentColor: '#d4661e',
      criticScore: 90,
      description: 'A brutal action-adventure set in 1500s Sengoku Japan.',
      longDescription: 'Sekiro: Shadows Die Twice puts players in the role of the "one-armed wolf," a disgraced warrior who must rescue his kidnapped lord. Built around a revolutionary posture and deflection combat system, the game demands precision and aggression. Winner of Game of the Year at The Game Awards 2019.',
      developer: 'FromSoftware',
      publisher: 'Activision',
      tags: JSON.stringify(['Souls-like', 'Ninja', 'Difficult', 'Singleplayer', 'Stealth']),
    },
    {
      title: 'Celeste',
      genres: JSON.stringify(['Platformer', 'Indie']),
      platforms: JSON.stringify(['PC', 'PS4', 'Xbox One', 'Nintendo Switch']),
      releaseYear: 2018,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/504230/header.jpg',
      coverGradient: 'linear-gradient(135deg, #0a1a3e 0%, #1a2a5e 40%, #5a8af0 100%)',
      accentColor: '#5a8af0',
      criticScore: 92,
      description: 'A narrative-driven platformer about climbing a mountain and overcoming inner demons.',
      longDescription: 'Celeste follows Madeline as she climbs the treacherous Celeste Mountain. The game features tight, responsive platforming, a heartfelt story about mental health and perseverance, and hundreds of challenging rooms. With an incredible soundtrack by Lena Raine and optional B-sides for hardcore players, Celeste is a modern platforming masterpiece.',
      developer: 'Maddy Makes Games',
      publisher: 'Maddy Makes Games',
      tags: JSON.stringify(['Platformer', 'Indie', 'Difficult', 'Pixel Art', 'Emotional']),
    },
    {
      title: 'Stardew Valley',
      genres: JSON.stringify(['Simulation', 'RPG']),
      platforms: JSON.stringify(['PC', 'PS4', 'Xbox One', 'Nintendo Switch']),
      releaseYear: 2016,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/413150/header.jpg',
      coverGradient: 'linear-gradient(135deg, #0a2a1a 0%, #1a4a2a 40%, #4caf50 100%)',
      accentColor: '#4caf50',
      criticScore: 89,
      description: 'Build the farm of your dreams in this charming farming RPG.',
      longDescription: 'Stardew Valley is a farming simulation RPG where you inherit your grandfather\'s old farm plot. Armed with hand-me-down tools, you set out to make a living off the land. Grow crops, raise livestock, mine for ores, sell goods, and build relationships with the townsfolk. Created entirely by one developer, ConcernedApe, the game has become one of the most beloved indie titles of all time.',
      developer: 'ConcernedApe',
      publisher: 'ConcernedApe',
      tags: JSON.stringify(['Farming', 'Relaxing', 'Pixel Art', 'Co-op', 'Life Sim']),
    },
    {
      title: 'Doom Eternal',
      genres: JSON.stringify(['FPS', 'Action']),
      platforms: JSON.stringify(['PC', 'PS4', 'Xbox One', 'Nintendo Switch']),
      releaseYear: 2020,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/782330/header.jpg',
      coverGradient: 'linear-gradient(135deg, #1a0a0a 0%, #3a0a0a 40%, #c62828 100%)',
      accentColor: '#c62828',
      criticScore: 88,
      description: 'Rip and tear through demonic hordes in this adrenaline-fueled FPS.',
      longDescription: 'Doom Eternal is a first-person shooter that demands aggression. As the Doom Slayer, you face Hell\'s armies across dimensions. The game introduces new mechanics like the Flame Belch, Blood Punch, and a grappling hook-equipped Super Shotgun. With a heavy metal soundtrack by Mick Gordon and relentless combat encounters, it\'s the ultimate power fantasy.',
      developer: 'id Software',
      publisher: 'Bethesda Softworks',
      tags: JSON.stringify(['FPS', 'Fast-Paced', 'Gore', 'Singleplayer', 'Demons']),
    },
    {
      title: 'Resident Evil Village',
      genres: JSON.stringify(['Horror', 'Action']),
      platforms: JSON.stringify(['PC', 'PS5', 'Xbox Series X']),
      releaseYear: 2021,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1196590/header.jpg',
      coverGradient: 'linear-gradient(135deg, #0a0a0a 0%, #1a1a2e 40%, #607d8b 100%)',
      accentColor: '#607d8b',
      criticScore: 84,
      description: 'Ethan Winters faces new horrors in a mysterious village in Europe.',
      longDescription: 'Resident Evil Village continues the story of Ethan Winters. Set in a snow-covered Eastern European village, the game blends survival horror with action as Ethan searches for his kidnapped daughter. Featuring iconic antagonists like Lady Dimitrescu, the game offers a diverse range of environments and gameplay styles across its chapters.',
      developer: 'Capcom',
      publisher: 'Capcom',
      tags: JSON.stringify(['Horror', 'Survival', 'FPS', 'Story Rich', 'Gothic']),
    },
    {
      title: 'Monster Hunter: World',
      genres: JSON.stringify(['Action', 'RPG']),
      platforms: JSON.stringify(['PC', 'PS4', 'Xbox One']),
      releaseYear: 2018,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/582010/header.jpg',
      coverGradient: 'linear-gradient(135deg, #0a1a0a 0%, #1a3a1a 40%, #ff9800 100%)',
      accentColor: '#ff9800',
      criticScore: 90,
      description: 'Hunt massive monsters in a living, breathing ecosystem.',
      longDescription: 'Monster Hunter: World drops players into a vibrant, living ecosystem where they take on fearsome monsters in thrilling battles. Craft powerful weapons and armor from monster parts, explore vast environments, and team up with friends in co-op hunts. The Iceborne expansion adds even more content to this already massive game.',
      developer: 'Capcom',
      publisher: 'Capcom',
      tags: JSON.stringify(['Co-op', 'Crafting', 'Boss Rush', 'Open World', 'Multiplayer']),
    },
    {
      title: 'Persona 5 Royal',
      genres: JSON.stringify(['RPG', 'Adventure']),
      platforms: JSON.stringify(['PC', 'PS5', 'Xbox Series X', 'Nintendo Switch']),
      releaseYear: 2020,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1687950/header.jpg',
      coverGradient: 'linear-gradient(135deg, #1a0a0a 0%, #3a0a1a 40%, #e91e63 100%)',
      accentColor: '#e91e63',
      criticScore: 95,
      description: 'Live a double life as a high school student and phantom thief in Tokyo.',
      longDescription: 'Persona 5 Royal is the definitive edition of Atlus\'s acclaimed JRPG. As Joker, lead the Phantom Thieves of Hearts to reform society by entering the cognitive palaces of corrupt adults. Features stylish turn-based combat, deep social simulation, an unforgettable cast, and over 100 hours of content. Royal adds new characters, story arcs, and quality-of-life improvements.',
      developer: 'Atlus',
      publisher: 'Sega',
      tags: JSON.stringify(['JRPG', 'Turn-Based', 'Story Rich', 'Anime', 'Social Sim']),
    },
    {
      title: 'Subnautica',
      genres: JSON.stringify(['Survival', 'Adventure']),
      platforms: JSON.stringify(['PC', 'PS4', 'Xbox One', 'Nintendo Switch']),
      releaseYear: 2018,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/264710/header.jpg',
      coverGradient: 'linear-gradient(135deg, #0a1a2e 0%, #0a2a4e 40%, #00bcd4 100%)',
      accentColor: '#00bcd4',
      criticScore: 87,
      description: 'Survive on an alien ocean world full of wonder and peril.',
      longDescription: 'Subnautica is an underwater survival adventure set on an alien ocean planet. After crash-landing, you must scavenge, craft, and explore the vast underwater world. Build habitats, pilot submarines, and discover the terrifying creatures lurking in the deep. The game masterfully blends exploration, survival, and environmental storytelling.',
      developer: 'Unknown Worlds',
      publisher: 'Unknown Worlds',
      tags: JSON.stringify(['Survival', 'Open World', 'Exploration', 'Underwater', 'Crafting']),
    },
    {
      title: 'Outer Wilds',
      genres: JSON.stringify(['Adventure', 'Puzzle']),
      platforms: JSON.stringify(['PC', 'PS4', 'Xbox One', 'Nintendo Switch']),
      releaseYear: 2019,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/753640/header.jpg',
      coverGradient: 'linear-gradient(135deg, #0a0a2e 0%, #1a1a4e 40%, #ff8f00 100%)',
      accentColor: '#ff8f00',
      criticScore: 85,
      description: 'Explore a solar system stuck in a time loop in this mystery adventure.',
      longDescription: 'Outer Wilds is an open-world mystery about a solar system trapped in an endless time loop. As an astronaut, you explore planets that change over time, uncover ancient alien ruins, and piece together the story of a long-dead civilization. Every 22 minutes, the sun explodes and the loop resets. Winner of multiple BAFTA awards.',
      developer: 'Mobius Digital',
      publisher: 'Annapurna Interactive',
      tags: JSON.stringify(['Exploration', 'Mystery', 'Space', 'Puzzle', 'Indie']),
    },
    {
      title: 'Ori and the Will of the Wisps',
      genres: JSON.stringify(['Metroidvania', 'Platformer']),
      platforms: JSON.stringify(['PC', 'Xbox One', 'Nintendo Switch']),
      releaseYear: 2020,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1057090/header.jpg',
      coverGradient: 'linear-gradient(135deg, #0a0a2e 0%, #1a2a5e 40%, #42a5f5 100%)',
      accentColor: '#42a5f5',
      criticScore: 93,
      description: 'An emotionally stunning platformer with breathtaking visuals and fluid combat.',
      longDescription: 'Ori and the Will of the Wisps continues the story of Ori, a guardian spirit. With gorgeous hand-painted art, a sweeping orchestral score, and refined combat and movement mechanics, the game elevates the metroidvania genre. Every environment is a visual masterpiece, and the story delivers powerful emotional moments.',
      developer: 'Moon Studios',
      publisher: 'Xbox Game Studios',
      tags: JSON.stringify(['Metroidvania', 'Beautiful', 'Emotional', 'Platformer', 'Indie']),
    },
    {
      title: 'Divinity: Original Sin 2',
      genres: JSON.stringify(['RPG', 'Strategy']),
      platforms: JSON.stringify(['PC', 'PS4', 'Xbox One', 'Nintendo Switch']),
      releaseYear: 2017,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/435150/header.jpg',
      coverGradient: 'linear-gradient(135deg, #0a0a1a 0%, #2a1a0a 40%, #bf360c 100%)',
      accentColor: '#bf360c',
      criticScore: 93,
      description: 'A deep, systemic RPG with unparalleled freedom and tactical turn-based combat.',
      longDescription: 'Divinity: Original Sin 2 is a masterclass in RPG design. With a fully reactive world, deep character customization, elemental combat interactions, and a branching narrative, it offers hundreds of hours of content. Play solo or with up to 3 friends in co-op, making choices that dramatically reshape the story.',
      developer: 'Larian Studios',
      publisher: 'Larian Studios',
      tags: JSON.stringify(['CRPG', 'Turn-Based', 'Co-op', 'Choices Matter', 'Fantasy']),
    },
    {
      title: 'Control',
      genres: JSON.stringify(['Action', 'Adventure']),
      platforms: JSON.stringify(['PC', 'PS5', 'Xbox Series X']),
      releaseYear: 2019,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/870780/header.jpg',
      coverGradient: 'linear-gradient(135deg, #0a0a1a 0%, #1a1a3e 40%, #b71c1c 100%)',
      accentColor: '#b71c1c',
      criticScore: 82,
      description: 'Wield supernatural powers in a shifting brutalist building as the new Director.',
      longDescription: 'Control puts you in the shoes of Jesse Faden, the new Director of the Federal Bureau of Control. The Oldest House, a shifting brutalist building in New York, has been invaded by a hostile force. Using telekinetic powers and a shape-shifting service weapon, you must reclaim the Bureau. Remedy Entertainment delivers a mind-bending action game with stunning destruction physics.',
      developer: 'Remedy Entertainment',
      publisher: '505 Games',
      tags: JSON.stringify(['Supernatural', 'Third-Person', 'Atmospheric', 'Story Rich', 'Physics']),
    },
    {
      title: 'Returnal',
      genres: JSON.stringify(['Roguelike', 'Action']),
      platforms: JSON.stringify(['PC', 'PS5']),
      releaseYear: 2021,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1649240/header.jpg',
      coverGradient: 'linear-gradient(135deg, #0a0a1a 0%, #0a1a2e 40%, #00897b 100%)',
      accentColor: '#00897b',
      criticScore: 86,
      description: 'A bullet-hell roguelike where every death sends you back to the beginning.',
      longDescription: 'Returnal is a third-person roguelike shooter set on an ever-shifting alien planet. As Selene, you crash-land on Atropos and find yourself trapped in a time loop. Each cycle presents new challenges, weapons, and story revelations. Combining bullet-hell gameplay with psychological horror, Returnal is one of the most innovative games on PS5.',
      developer: 'Housemarque',
      publisher: 'Sony Interactive',
      tags: JSON.stringify(['Roguelike', 'Bullet Hell', 'Sci-Fi', 'Difficult', 'Atmospheric']),
    },
    {
      title: 'It Takes Two',
      genres: JSON.stringify(['Platformer', 'Adventure']),
      platforms: JSON.stringify(['PC', 'PS5', 'Xbox Series X']),
      releaseYear: 2021,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1426210/header.jpg',
      coverGradient: 'linear-gradient(135deg, #1a0a2e 0%, #2a1a4e 40%, #ab47bc 100%)',
      accentColor: '#ab47bc',
      criticScore: 88,
      description: 'A co-op adventure where a couple must work together to save their relationship.',
      longDescription: 'It Takes Two is a co-op only platformer about Cody and May, a couple on the brink of divorce who get magically transformed into dolls. Together, they must navigate fantastical worlds, each featuring unique gameplay mechanics. Winner of Game of the Year at The Game Awards 2021, it reinvents co-op gaming with constant variety.',
      developer: 'Hazelight Studios',
      publisher: 'Electronic Arts',
      tags: JSON.stringify(['Co-op', 'Platformer', 'Split Screen', 'Story Rich', 'Family']),
    },
    {
      title: 'Horizon Zero Dawn',
      genres: JSON.stringify(['Action', 'RPG']),
      platforms: JSON.stringify(['PC', 'PS4']),
      releaseYear: 2017,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1151640/header.jpg',
      coverGradient: 'linear-gradient(135deg, #0a1a1a 0%, #1a3a2a 40%, #66bb6a 100%)',
      accentColor: '#66bb6a',
      criticScore: 89,
      description: 'Hunt machines in a post-apocalyptic world reclaimed by nature.',
      longDescription: 'Horizon Zero Dawn puts players in a lush, post-apocalyptic world where nature has reclaimed the ruins of civilization and mechanical creatures roam the land. As Aloy, an outcast hunter, you must uncover the mysteries of the ancient past. Featuring strategic combat, a gripping story, and a stunning open world.',
      developer: 'Guerrilla Games',
      publisher: 'Sony Interactive',
      tags: JSON.stringify(['Open World', 'Post-Apocalyptic', 'Robot Dinosaurs', 'Story Rich', 'Female Protagonist']),
    },
    {
      title: 'Terraria',
      genres: JSON.stringify(['Sandbox', 'Adventure']),
      platforms: JSON.stringify(['PC', 'PS4', 'Xbox One', 'Nintendo Switch']),
      releaseYear: 2011,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/105600/header.jpg',
      coverGradient: 'linear-gradient(135deg, #0a2a1a 0%, #1a4a3a 40%, #26a69a 100%)',
      accentColor: '#26a69a',
      criticScore: 83,
      description: 'Dig, fight, explore, build — the world is your canvas in this 2D sandbox.',
      longDescription: 'Terraria is a 2D sandbox game with gameplay revolving around exploration, building, crafting, combat, and mining. With procedurally generated worlds, hundreds of enemies, thousands of items, and extensive boss battles, the game offers near-infinite replayability. Years of free updates have made it one of the most content-rich games ever created.',
      developer: 'Re-Logic',
      publisher: 'Re-Logic',
      tags: JSON.stringify(['Sandbox', 'Crafting', 'Co-op', 'Pixel Art', '2D']),
    },
    {
      title: 'Valheim',
      genres: JSON.stringify(['Survival', 'Adventure']),
      platforms: JSON.stringify(['PC']),
      releaseYear: 2021,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/892970/header.jpg',
      coverGradient: 'linear-gradient(135deg, #0a1a1a 0%, #1a2a2e 40%, #546e7a 100%)',
      accentColor: '#546e7a',
      criticScore: 80,
      description: 'A brutal Viking survival game set in a procedurally-generated purgatory.',
      longDescription: 'Valheim is a Viking survival game for 1-10 players, set in a procedurally-generated world inspired by Norse mythology. Build mead halls, craft weapons, sail the seas, and defeat mythical bosses to prove yourself worthy of Valhalla. Its lo-fi art style combined with atmospheric lighting creates a uniquely beautiful world.',
      developer: 'Iron Gate Studio',
      publisher: 'Coffee Stain Publishing',
      tags: JSON.stringify(['Survival', 'Viking', 'Co-op', 'Crafting', 'Open World']),
    },
    {
      title: 'Half-Life: Alyx',
      genres: JSON.stringify(['FPS', 'Adventure']),
      platforms: JSON.stringify(['PC']),
      releaseYear: 2020,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/546560/header.jpg',
      coverGradient: 'linear-gradient(135deg, #0a0a1a 0%, #1a1a3e 40%, #ff5722 100%)',
      accentColor: '#ff5722',
      criticScore: 93,
      description: 'A VR masterpiece set between Half-Life 1 and 2.',
      longDescription: 'Half-Life: Alyx is Valve\'s return to the Half-Life series, built from the ground up for virtual reality. As Alyx Vance, you fight the Combine in City 17 with physics-based puzzles, intense combat, and environmental storytelling that only VR can deliver. Widely regarded as the best VR game ever made.',
      developer: 'Valve',
      publisher: 'Valve',
      tags: JSON.stringify(['VR', 'FPS', 'Sci-Fi', 'Story Rich', 'Physics']),
    },
    {
      title: 'Slay the Spire',
      genres: JSON.stringify(['Roguelike', 'Strategy']),
      platforms: JSON.stringify(['PC', 'PS4', 'Xbox One', 'Nintendo Switch']),
      releaseYear: 2019,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/646570/header.jpg',
      coverGradient: 'linear-gradient(135deg, #0a0a1a 0%, #1a1a2e 40%, #8d6e63 100%)',
      accentColor: '#8d6e63',
      criticScore: 89,
      description: 'A fusion of roguelike and deck-building that defined a genre.',
      longDescription: 'Slay the Spire pioneered the deck-building roguelike genre. Choose a character, build a deck of powerful cards, discover relics, and climb the ever-changing Spire. With four distinct characters, hundreds of cards, and infinite strategic variety, each run is a unique puzzle. The game spawned countless imitators but remains the gold standard.',
      developer: 'Mega Crit',
      publisher: 'Mega Crit',
      tags: JSON.stringify(['Roguelike', 'Card Game', 'Strategy', 'Indie', 'Deckbuilder']),
    },
    {
      title: 'The Last of Us Part I',
      genres: JSON.stringify(['Action', 'Adventure']),
      platforms: JSON.stringify(['PC', 'PS5']),
      releaseYear: 2022,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1888930/header.jpg',
      coverGradient: 'linear-gradient(135deg, #0a0a0a 0%, #1a1a1a 40%, #558b2f 100%)',
      accentColor: '#558b2f',
      criticScore: 88,
      description: 'A masterful story of survival and connection in a post-pandemic world.',
      longDescription: 'The Last of Us Part I is a rebuilt-from-the-ground-up remake of Naughty Dog\'s landmark 2013 game. Joel, a hardened survivor, is hired to smuggle Ellie, a 14-year-old girl, out of an oppressive quarantine zone. What starts as a small job becomes a brutal journey across a devastated America. Features completely rebuilt graphics, AI, and gameplay.',
      developer: 'Naughty Dog',
      publisher: 'Sony Interactive',
      tags: JSON.stringify(['Story Rich', 'Post-Apocalyptic', 'Stealth', 'Emotional', 'Cinematic']),
    },
    {
      title: 'Cuphead',
      genres: JSON.stringify(['Action', 'Platformer']),
      platforms: JSON.stringify(['PC', 'PS4', 'Xbox One', 'Nintendo Switch']),
      releaseYear: 2017,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/268910/header.jpg',
      coverGradient: 'linear-gradient(135deg, #2e1a0a 0%, #4e2a0a 40%, #ff6f00 100%)',
      accentColor: '#ff6f00',
      criticScore: 86,
      description: 'A run-and-gun game inspired by 1930s cartoons with stunning hand-drawn art.',
      longDescription: 'Cuphead is a classic run-and-gun action game heavily focused on boss battles. Inspired by cartoons of the 1930s, every frame is hand-drawn and inked using the same techniques used in the era. The game features challenging gameplay, a jazzy original soundtrack, and the Delicious Last Course DLC expands it significantly.',
      developer: 'Studio MDHR',
      publisher: 'Studio MDHR',
      tags: JSON.stringify(['Difficult', 'Hand-Drawn', 'Boss Rush', 'Co-op', 'Retro']),
    },
    {
      title: 'Titanfall 2',
      genres: JSON.stringify(['FPS', 'Action']),
      platforms: JSON.stringify(['PC', 'PS4', 'Xbox One']),
      releaseYear: 2016,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1237970/header.jpg',
      coverGradient: 'linear-gradient(135deg, #0a0a1a 0%, #1a2a3e 40%, #ff6d00 100%)',
      accentColor: '#ff6d00',
      criticScore: 89,
      description: 'A masterful FPS with wall-running pilots and massive Titans.',
      longDescription: 'Titanfall 2 features one of the greatest FPS campaigns ever made. The bond between pilot Jack Cooper and Titan BT-7274 drives a story through innovative level design, including the time-travel level "Effect and Cause." The multiplayer combines fast-paced pilot movement with devastating Titan warfare for an unmatched experience.',
      developer: 'Respawn Entertainment',
      publisher: 'Electronic Arts',
      tags: JSON.stringify(['FPS', 'Mech', 'Multiplayer', 'Campaign', 'Fast-Paced']),
    },
    {
      title: 'Deep Rock Galactic',
      genres: JSON.stringify(['FPS', 'Co-op']),
      platforms: JSON.stringify(['PC', 'PS4', 'PS5', 'Xbox One']),
      releaseYear: 2020,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/548430/header.jpg',
      coverGradient: 'linear-gradient(135deg, #1a1a0a 0%, #3a2a0a 40%, #ffa000 100%)',
      accentColor: '#ffa000',
      criticScore: 85,
      description: 'Space dwarves mine, shoot, and drink beer in procedurally generated caves.',
      longDescription: 'Deep Rock Galactic is a 1-4 player co-op FPS featuring badass space dwarves, 100% destructible environments, procedurally generated caves, and endless hordes of alien monsters. Choose from four classes, dig through fully destructible terrain, and complete objectives while fighting for survival. Rock and Stone!',
      developer: 'Ghost Ship Games',
      publisher: 'Coffee Stain Publishing',
      tags: JSON.stringify(['Co-op', 'FPS', 'Mining', 'Procedural', 'Class-Based']),
    },
    {
      title: 'Shovel Knight',
      genres: JSON.stringify(['Platformer', 'Action']),
      platforms: JSON.stringify(['PC', 'PS4', 'Xbox One', 'Nintendo Switch']),
      releaseYear: 2014,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/250760/header.jpg',
      coverGradient: 'linear-gradient(135deg, #0a0a2e 0%, #1a1a4e 40%, #2979ff 100%)',
      accentColor: '#2979ff',
      criticScore: 85,
      description: 'A lovingly crafted homage to retro action-platformers.',
      longDescription: 'Shovel Knight is a sweeping classic action-adventure game with awesome gameplay, memorable characters, and an 8-bit retro aesthetic. Run, jump, and slash your way through a world of treasure and discovery. With multiple free expansions featuring playable campaigns, it offers tremendous value and replayability.',
      developer: 'Yacht Club Games',
      publisher: 'Yacht Club Games',
      tags: JSON.stringify(['Retro', 'Platformer', '2D', 'Indie', 'Boss Rush']),
    },
    {
      title: 'Factorio',
      genres: JSON.stringify(['Strategy', 'Simulation']),
      platforms: JSON.stringify(['PC']),
      releaseYear: 2020,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/427520/header.jpg',
      coverGradient: 'linear-gradient(135deg, #0a1a1a 0%, #1a2a2a 40%, #ff6e40 100%)',
      accentColor: '#ff6e40',
      criticScore: 90,
      description: 'Build and maintain factories on an alien planet in this addictive automation game.',
      longDescription: 'Factorio is a game about building and creating automated factories to produce increasingly complex items. Use your imagination to design your factory, combine simple elements into ingenious structures, and protect it from alien creatures. With multiplayer support and an incredibly active modding community, it\'s one of the highest-rated games on Steam.',
      developer: 'Wube Software',
      publisher: 'Wube Software',
      tags: JSON.stringify(['Automation', 'Base Building', 'Strategy', 'Sandbox', 'Multiplayer']),
    },
    {
      title: 'Neon White',
      genres: JSON.stringify(['FPS', 'Platformer']),
      platforms: JSON.stringify(['PC', 'PS4', 'PS5', 'Nintendo Switch']),
      releaseYear: 2022,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1533420/header.jpg',
      coverGradient: 'linear-gradient(135deg, #1a0a1a 0%, #3a1a3a 40%, #f50057 100%)',
      accentColor: '#f50057',
      criticScore: 88,
      description: 'A lightning-fast FPS platformer about exterminating demons in Heaven.',
      longDescription: 'Neon White is a single-player speedrunning FPS where you\'re an assassin plucked from Hell to compete with other demon slayers for a chance to live in Heaven. Each level is a puzzle solved by choosing the right cards (weapons) and finding the fastest route. With anime-inspired storytelling and incredibly tight gameplay, it\'s built for replaying and optimizing.',
      developer: 'Angel Matrix',
      publisher: 'Annapurna Interactive',
      tags: JSON.stringify(['Speedrun', 'FPS', 'Anime', 'Card Game', 'Singleplayer']),
    },
    {
      title: 'Resident Evil 4 Remake',
      genres: JSON.stringify(['Horror', 'Action']),
      platforms: JSON.stringify(['PC', 'PS5', 'Xbox Series X']),
      releaseYear: 2023,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/2050650/header.jpg',
      coverGradient: 'linear-gradient(135deg, #0a0a0a 0%, #1a0a1a 40%, #880e4f 100%)',
      accentColor: '#880e4f',
      criticScore: 93,
      description: 'A masterful reimagining of the survival horror classic.',
      longDescription: 'Resident Evil 4 Remake modernizes the 2005 classic with stunning RE Engine graphics, reimagined gameplay, and expanded story elements. Leon S. Kennedy journeys to a rural village in Spain to rescue the president\'s kidnapped daughter. With tense combat, clever puzzles, and terrifying enemies, Capcom once again proves why RE4 is legendary.',
      developer: 'Capcom',
      publisher: 'Capcom',
      tags: JSON.stringify(['Horror', 'Survival', 'Remake', 'Third-Person', 'Action']),
    },
    {
      title: 'Undertale',
      genres: JSON.stringify(['RPG', 'Indie']),
      platforms: JSON.stringify(['PC', 'PS4', 'Nintendo Switch']),
      releaseYear: 2015,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/391540/header.jpg',
      coverGradient: 'linear-gradient(135deg, #0a0a0a 0%, #1a0a2e 40%, #9c27b0 100%)',
      accentColor: '#9c27b0',
      criticScore: 92,
      description: 'A revolutionary RPG where nobody has to die.',
      longDescription: 'Undertale is an RPG where you don\'t have to kill anyone. Each enemy can be defeated non-violently through a unique MERCY system. Your choices genuinely matter, fundamentally altering the story and world. Created entirely by Toby Fox, the game features memorable characters, a brilliant soundtrack, and multiple endings that respond to your actions.',
      developer: 'Toby Fox',
      publisher: 'Toby Fox',
      tags: JSON.stringify(['RPG', 'Indie', 'Story Rich', 'Choices Matter', 'Pixel Art']),
    },
    {
      title: 'Portal 2',
      genres: JSON.stringify(['Puzzle', 'FPS']),
      platforms: JSON.stringify(['PC', 'PS3', 'Xbox 360']),
      releaseYear: 2011,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/620/header.jpg',
      coverGradient: 'linear-gradient(135deg, #0a0a1a 0%, #1a2a4e 40%, #2196f3 100%)',
      accentColor: '#2196f3',
      criticScore: 95,
      description: 'A mind-bending puzzle game with brilliant writing and portal mechanics.',
      longDescription: 'Portal 2 is a first-person puzzle-platform game. It builds on the original with new mechanics including gels, light bridges, and tractor beams. The single-player campaign features GLaDOS, Wheatley, and Cave Johnson in one of gaming\'s funniest scripts. A full co-op campaign with Atlas and P-body doubles the content. Widely considered one of the greatest games ever made.',
      developer: 'Valve',
      publisher: 'Valve',
      tags: JSON.stringify(['Puzzle', 'Co-op', 'Comedy', 'Sci-Fi', 'Physics']),
    },
    {
      title: 'RimWorld',
      genres: JSON.stringify(['Strategy', 'Simulation']),
      platforms: JSON.stringify(['PC']),
      releaseYear: 2018,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/294100/header.jpg',
      coverGradient: 'linear-gradient(135deg, #0a1a1a 0%, #1a2a3a 40%, #78909c 100%)',
      accentColor: '#78909c',
      criticScore: 86,
      description: 'A sci-fi colony sim driven by an intelligent AI storyteller.',
      longDescription: 'RimWorld is a sci-fi colony sim driven by an intelligent AI storyteller. You begin with three survivors of a shipwreck on a distant world. Manage colonists\' needs, moods, wounds, and relationships. Build defenses against raiders and ancient dangers. Every playthrough generates unique, memorable stories. With extraordinary mod support, the game is endlessly replayable.',
      developer: 'Ludeon Studios',
      publisher: 'Ludeon Studios',
      tags: JSON.stringify(['Colony Sim', 'Strategy', 'Sandbox', 'Modding', 'Story Generator']),
    },
    {
      title: 'Bloodborne',
      genres: JSON.stringify(['RPG', 'Action']),
      platforms: JSON.stringify(['PS4']),
      releaseYear: 2015,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/2963760/header.jpg',
      coverGradient: 'linear-gradient(135deg, #0a0a0a 0%, #1a0a1a 40%, #880e4f 100%)',
      accentColor: '#b71c1c',
      criticScore: 92,
      description: 'A gothic horror action RPG set in a nightmarish Victorian city.',
      longDescription: 'Bloodborne takes the Souls formula and drenches it in Lovecraftian horror. Set in the decaying city of Yharnam, players must unravel its gruesome mystery as the night unfolds. Unlike Dark Souls, combat rewards aggression with a rally mechanic. Featuring some of the most memorable boss fights in gaming and a chilling world of beasts and cosmic horror.',
      developer: 'FromSoftware',
      publisher: 'Sony Interactive',
      tags: JSON.stringify(['Souls-like', 'Gothic', 'Horror', 'Difficult', 'Lovecraftian']),
    },
    {
      title: 'Prey',
      genres: JSON.stringify(['FPS', 'RPG']),
      platforms: JSON.stringify(['PC', 'PS4', 'Xbox One']),
      releaseYear: 2017,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/480490/header.jpg',
      coverGradient: 'linear-gradient(135deg, #0a0a0a 0%, #0a0a2e 40%, #424242 100%)',
      accentColor: '#9e9e9e',
      criticScore: 82,
      description: 'An immersive sim set aboard a space station overrun by shape-shifting aliens.',
      longDescription: 'Prey is a first-person sci-fi action game set aboard Talos I, a space station orbiting the moon. As Morgan Yu, you uncover the truth about an alien threat while navigating a vast, interconnected station. With powers gained from studying the aliens, multiple approaches to every problem, and a story full of twists, Prey is a spiritual successor to System Shock.',
      developer: 'Arkane Studios',
      publisher: 'Bethesda Softworks',
      tags: JSON.stringify(['Immersive Sim', 'Sci-Fi', 'Exploration', 'Horror', 'FPS']),
    },
    {
      title: 'Inscryption',
      genres: JSON.stringify(['Strategy', 'Horror']),
      platforms: JSON.stringify(['PC', 'PS4', 'PS5', 'Nintendo Switch']),
      releaseYear: 2021,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1092790/header.jpg',
      coverGradient: 'linear-gradient(135deg, #0a0a0a 0%, #1a1a1a 40%, #4e342e 100%)',
      accentColor: '#6d4c41',
      criticScore: 86,
      description: 'A darkly surreal card game that transcends its own genre.',
      longDescription: 'Inscryption is an inky black card-based odyssey that blends the deckbuilding roguelike, escape-room puzzles, and psychological horror into a blood-laced smoothie. The less you know going in, the better. What starts as a simple cabin card game evolves into something entirely unexpected, shattering the fourth wall in ways that will leave you stunned.',
      developer: 'Daniel Mullins Games',
      publisher: 'Devolver Digital',
      tags: JSON.stringify(['Card Game', 'Horror', 'Meta', 'Puzzle', 'Indie']),
    },
    {
      title: 'Hitman 3',
      genres: JSON.stringify(['Stealth', 'Action']),
      platforms: JSON.stringify(['PC', 'PS5', 'Xbox Series X']),
      releaseYear: 2021,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1659040/header.jpg',
      coverGradient: 'linear-gradient(135deg, #0a0a0a 0%, #1a1a1a 40%, #c62828 100%)',
      accentColor: '#c62828',
      criticScore: 87,
      description: 'The conclusion to the World of Assassination trilogy.',
      longDescription: 'Hitman 3 concludes the World of Assassination trilogy with six stunning sandbox locations. As Agent 47, use disguises, environmental kills, and creative problem-solving to eliminate targets. Each level is a intricate puzzle box with dozens of approaches. The game includes access to all Hitman 1 and 2 levels, creating the ultimate stealth sandbox.',
      developer: 'IO Interactive',
      publisher: 'IO Interactive',
      tags: JSON.stringify(['Stealth', 'Sandbox', 'Assassination', 'Replayable', 'Third-Person']),
    },
    {
      title: 'Tunic',
      genres: JSON.stringify(['Action', 'Adventure']),
      platforms: JSON.stringify(['PC', 'PS4', 'PS5', 'Xbox One', 'Nintendo Switch']),
      releaseYear: 2022,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/553420/header.jpg',
      coverGradient: 'linear-gradient(135deg, #0a2a1a 0%, #1a4a2a 40%, #43a047 100%)',
      accentColor: '#43a047',
      criticScore: 85,
      description: 'An isometric action game about a little fox on a big adventure.',
      longDescription: 'Tunic is an isometric action game starring a small fox who finds a big sword. Explore a world filled with lost legends, treasure, and fearsome monsters. Discover an in-game instruction manual written in a mysterious language that gradually reveals the game\'s secrets. What appears to be a simple adventure hides deep puzzles and surprising challenges.',
      developer: 'Andrew Shouldice',
      publisher: 'Finji',
      tags: JSON.stringify(['Adventure', 'Puzzle', 'Indie', 'Souls-like', 'Isometric']),
    },
    {
      title: 'Death Stranding',
      genres: JSON.stringify(['Action', 'Adventure']),
      platforms: JSON.stringify(['PC', 'PS4', 'PS5']),
      releaseYear: 2019,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1190460/header.jpg',
      coverGradient: 'linear-gradient(135deg, #0a0a1a 0%, #1a1a2e 40%, #90a4ae 100%)',
      accentColor: '#90a4ae',
      criticScore: 82,
      description: 'Hideo Kojima\'s genre-defying game about reconnecting a fractured world.',
      longDescription: 'Death Stranding is a genre-defying experience from Hideo Kojima. As Sam Porter Bridges, you traverse a ravaged America to reconnect isolated cities and a fragmented society. Carrying packages across treacherous terrain becomes meditative and meaningful. With a star-studded cast and themes of connection, the game is unlike anything else in gaming.',
      developer: 'Kojima Productions',
      publisher: 'Sony Interactive',
      tags: JSON.stringify(['Open World', 'Walking Sim', 'Sci-Fi', 'Strand Game', 'Cinematic']),
    },
    {
      title: 'Psychonauts 2',
      genres: JSON.stringify(['Platformer', 'Adventure']),
      platforms: JSON.stringify(['PC', 'PS4', 'Xbox One']),
      releaseYear: 2021,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/607080/header.jpg',
      coverGradient: 'linear-gradient(135deg, #1a0a2e 0%, #2a1a4e 40%, #7e57c2 100%)',
      accentColor: '#7e57c2',
      criticScore: 87,
      description: 'A wildly imaginative platformer set inside the minds of eccentric characters.',
      longDescription: 'Psychonauts 2 is a 3D platformer from the mind of Tim Schafer. As Raz, a young psychic, you dive into the minds of friends and foes to battle inner demons and unravel conspiracies. Each mental world is uniquely themed and visually inventive, from psychedelic concerts to sensory overload hospitals. Hilarious writing and heartfelt storytelling.',
      developer: 'Double Fine Productions',
      publisher: 'Xbox Game Studios',
      tags: JSON.stringify(['Platformer', 'Comedy', 'Psychedelic', 'Story Rich', 'Indie']),
    },
    {
      title: 'Sifu',
      genres: JSON.stringify(['Action', 'Fighting']),
      platforms: JSON.stringify(['PC', 'PS4', 'PS5', 'Nintendo Switch']),
      releaseYear: 2022,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/2138710/header.jpg',
      coverGradient: 'linear-gradient(135deg, #0a0a0a 0%, #1a1a2e 40%, #ef6c00 100%)',
      accentColor: '#ef6c00',
      criticScore: 80,
      description: 'A martial arts action game where every death ages your character.',
      longDescription: 'Sifu is a third-person action game with unique roguelike elements. Play as a young kung-fu student seeking vengeance, with a magical pendant that resurrects you at a cost: each death makes you older. Master the fluid hand-to-hand combat, learn dodge timings, and use environmental objects to fight your way through five distinct chapters. Die too many times, and it\'s game over.',
      developer: 'Sloclap',
      publisher: 'Sloclap',
      tags: JSON.stringify(['Martial Arts', 'Difficult', 'Beat Em Up', 'Roguelike', 'Singleplayer']),
    },
    {
      title: 'Noita',
      genres: JSON.stringify(['Roguelike', 'Action']),
      platforms: JSON.stringify(['PC']),
      releaseYear: 2020,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/881100/header.jpg',
      coverGradient: 'linear-gradient(135deg, #1a0a0a 0%, #2e1a0a 40%, #e65100 100%)',
      accentColor: '#e65100',
      criticScore: 80,
      description: 'A magical action roguelike where every pixel is physically simulated.',
      longDescription: 'Noita is a magical action roguelike set in a world where every pixel is physically simulated. Fight your way through procedurally generated environments, discover random wand combinations and spells, and unleash environmental chaos. Fire, water, acid, lava — everything interacts with everything else. The depth of secrets and hidden content is staggering.',
      developer: 'Nolla Games',
      publisher: 'Nolla Games',
      tags: JSON.stringify(['Roguelike', 'Physics', 'Pixel Art', 'Procedural', 'Difficult']),
    },
    {
      title: 'Spiritfarer',
      genres: JSON.stringify(['Adventure', 'Simulation']),
      platforms: JSON.stringify(['PC', 'PS4', 'Xbox One', 'Nintendo Switch']),
      releaseYear: 2020,
      coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/972660/header.jpg',
      coverGradient: 'linear-gradient(135deg, #1a0a2e 0%, #2a1a3e 40%, #ce93d8 100%)',
      accentColor: '#ce93d8',
      criticScore: 84,
      description: 'A cozy management game about dying, where you ferry spirits to the afterlife.',
      longDescription: 'Spiritfarer is a cozy management game about dying. You play Stella, ferrymaster to the deceased. Build a boat to explore the world, care for your spirit passengers, and help them feel ready to pass on. Cook, farm, fish, mine, and weave — all while learning the stories of the spirits aboard. Beautiful hand-drawn animation and an emotional story about letting go.',
      developer: 'Thunder Lotus Games',
      publisher: 'Thunder Lotus Games',
      tags: JSON.stringify(['Cozy', 'Emotional', 'Management', 'Hand-Drawn', 'Co-op']),
    },
  ];

  const games = [];
  for (const data of gamesData) {
    const game = await prisma.game.create({ data });
    games.push(game);
  }

  console.log(`✅ Created ${games.length} games`);

  // Seed reviews
  const reviewsData: { gameIndex: number; userIndex: number; score: number; body: string; helpfulVotes: number }[] = [
    // Elden Ring
    { gameIndex: 0, userIndex: 0, score: 10, body: 'Elden Ring redefines the open-world RPG. Every cave, every ruin, every boss feels handcrafted and meaningful. FromSoftware\'s magnum opus.', helpfulVotes: 42 },
    { gameIndex: 0, userIndex: 1, score: 9, body: 'The exploration is unmatched. I spent 200 hours and still found new things. Combat is punishing but fair. A masterpiece that respects the player.', helpfulVotes: 38 },
    { gameIndex: 0, userIndex: 2, score: 8, body: 'Stunning world design and lore. The late game bosses can feel unfair at times, but the journey to get there is worth every death.', helpfulVotes: 25 },
    { gameIndex: 0, userIndex: 3, score: 10, body: 'Speedrunning this game has been incredible. The amount of sequence breaks and routes you can take shows how well-designed the world is.', helpfulVotes: 18 },
    // Cyberpunk 2077
    { gameIndex: 1, userIndex: 0, score: 8, body: 'After the patches, this game is genuinely amazing. Night City is the most atmospheric open world I\'ve ever seen. Phantom Liberty elevated it further.', helpfulVotes: 30 },
    { gameIndex: 1, userIndex: 2, score: 7, body: 'The narrative is CD Projekt Red at their best. The side quests rival main quests in other games. Still some jank, but the story hits hard.', helpfulVotes: 22 },
    { gameIndex: 1, userIndex: 4, score: 9, body: 'Night City feels alive in a way no other game world does. The character writing is phenomenal — Judy, Panam, and Johnny are unforgettable.', helpfulVotes: 35 },
    // Hollow Knight
    { gameIndex: 2, userIndex: 1, score: 10, body: 'The best metroidvania ever made, period. The art, the music, the tight controls, the sheer amount of content for the price — it\'s a gift to gaming.', helpfulVotes: 55 },
    { gameIndex: 2, userIndex: 3, score: 9, body: 'Speedrunning Hollow Knight never gets old. The movement tech is so satisfying. Path of Pain is the ultimate test. Cannot wait for Silksong.', helpfulVotes: 20 },
    { gameIndex: 2, userIndex: 4, score: 8, body: 'Hallownest is one of the most atmospheric game worlds ever created. The lore runs deep and the boss design is challenging but rewarding.', helpfulVotes: 28 },
    { gameIndex: 2, userIndex: 0, score: 9, body: 'Team Cherry created a masterclass in game design. Every zone has its own identity. The Grimm Troupe DLC is pure perfection.', helpfulVotes: 15 },
    // Hades
    { gameIndex: 3, userIndex: 0, score: 10, body: 'Supergiant outdid themselves. The way narrative weaves into the roguelike loop is revolutionary. Every death feels like progress, not punishment.', helpfulVotes: 44 },
    { gameIndex: 3, userIndex: 1, score: 9, body: 'The weapon system keeps every run fresh. The voice acting is god-tier. Literally — you\'re talking to gods and it sounds incredible every time.', helpfulVotes: 32 },
    { gameIndex: 3, userIndex: 4, score: 10, body: 'Best roguelike ever made. The cast of characters is unforgettable, the combat is tight, and the art direction is jaw-dropping. Pure perfection.', helpfulVotes: 48 },
    // God of War
    { gameIndex: 4, userIndex: 0, score: 9, body: 'The relationship between Kratos and Atreus is gaming\'s best father-son story. One continuous camera shot. Emotional, brutal, and beautiful.', helpfulVotes: 40 },
    { gameIndex: 4, userIndex: 2, score: 10, body: 'Santa Monica reinvented Kratos in the best possible way. The Leviathan Axe might be the most satisfying weapon in gaming history.', helpfulVotes: 52 },
    { gameIndex: 4, userIndex: 3, score: 8, body: 'Great cinematic experience. The optional Valkyrie fights are the real endgame challenge. Sigrun is one of the hardest bosses in modern gaming.', helpfulVotes: 26 },
    // Red Dead Redemption 2
    { gameIndex: 5, userIndex: 0, score: 10, body: 'Arthur Morgan\'s story is the greatest narrative in gaming. The world feels alive — I spent hours just riding through the wilderness at sunset.', helpfulVotes: 60 },
    { gameIndex: 5, userIndex: 2, score: 9, body: 'Rockstar created a living, breathing world. Every NPC has a routine. Every animal behaves realistically. It sets a new standard for immersion.', helpfulVotes: 45 },
    { gameIndex: 5, userIndex: 4, score: 10, body: 'The attention to detail is staggering. Horse balls shrink in cold weather. That tells you everything about the level of care in this game.', helpfulVotes: 38 },
    { gameIndex: 5, userIndex: 1, score: 8, body: 'Beautiful world and story, though the mission structure feels restrictive for such an open world. The epilogue is a perfect sendoff.', helpfulVotes: 22 },
    // Baldur's Gate 3
    { gameIndex: 6, userIndex: 2, score: 10, body: 'Larian Studios created the definitive CRPG. The freedom of choice is staggering — every playthrough reveals new paths and consequences.', helpfulVotes: 50 },
    { gameIndex: 6, userIndex: 0, score: 9, body: 'D&D in video game form, done right at last. The companion writing is industry-leading. Astarion and Shadowheart are iconic characters.', helpfulVotes: 40 },
    { gameIndex: 6, userIndex: 4, score: 10, body: 'Act 1 alone has more content than most full games. Co-op with friends is chaotic and brilliant. GOTY 2023, no question.', helpfulVotes: 55 },
    { gameIndex: 6, userIndex: 1, score: 9, body: 'The environmental interaction system is genius. Stacking barrels of explosives to one-shot a boss? That\'s not a bug, it\'s a feature.', helpfulVotes: 33 },
    // Disco Elysium
    { gameIndex: 7, userIndex: 2, score: 10, body: 'The most brilliantly written game I\'ve ever played. Your skills literally argue with each other in your head. There\'s nothing else like it in gaming.', helpfulVotes: 62 },
    { gameIndex: 7, userIndex: 0, score: 9, body: 'A game where you can fail at everything and still have a compelling story. The political systems and dialogue trees are deep and thought-provoking.', helpfulVotes: 35 },
    { gameIndex: 7, userIndex: 4, score: 8, body: 'Not for everyone — there\'s zero combat. But if you love great writing and meaningful choices, this is the best RPG you\'ll ever play.', helpfulVotes: 28 },
    // Dead Cells
    { gameIndex: 8, userIndex: 3, score: 10, body: 'The best combat feel in any 2D game. Every weapon has weight, every dodge is precise. Speedrunning Dead Cells is pure adrenaline.', helpfulVotes: 30 },
    { gameIndex: 8, userIndex: 1, score: 9, body: 'Motion Twin keeps adding content years later. The weapon variety is insane and the pixel art is gorgeous. A roguelike that never gets stale.', helpfulVotes: 25 },
    { gameIndex: 8, userIndex: 4, score: 8, body: 'Tight controls, challenging but fair difficulty, and incredible replay value. The metroidvania elements add great exploration to the roguelike loop.', helpfulVotes: 20 },
    // Into the Breach
    { gameIndex: 9, userIndex: 2, score: 9, body: 'Chess meets Pacific Rim. Every move matters, every decision has consequences. The perfect information system removes RNG frustration entirely.', helpfulVotes: 35 },
    { gameIndex: 9, userIndex: 0, score: 8, body: 'Incredible tactical depth in a small package. Each mech squad plays completely differently. Subset Games proved small scale can be deeply strategic.', helpfulVotes: 22 },
    { gameIndex: 9, userIndex: 3, score: 9, body: 'The most elegant strategy game I\'ve played. Simple rules, deep tactics. Perfect for quick sessions or marathon play. A masterpiece of game design.', helpfulVotes: 28 },
    // ── Reviews for 40 new games ──────────────────────────────────
    // The Witcher 3 (index 10)
    { gameIndex: 10, userIndex: 0, score: 10, body: 'The gold standard for open-world RPGs. Geralt\'s story in the Eyes of Novigrad alone rivals entire games. Hearts of Stone is the best DLC ever made.', helpfulVotes: 58 },
    { gameIndex: 10, userIndex: 2, score: 9, body: 'The Bloody Baron questline is some of the best writing in any medium. The world feels alive and every sidequest tells a meaningful story.', helpfulVotes: 45 },
    { gameIndex: 10, userIndex: 4, score: 10, body: 'Blood and Wine is basically a full game disguised as DLC. Toussaint is gorgeous. CDPR gave us hundreds of hours of perfection.', helpfulVotes: 52 },
    // Dark Souls III (index 11)
    { gameIndex: 11, userIndex: 1, score: 9, body: 'The Nameless King is the greatest boss fight in the series. Faster combat than DS1 and DS2 with the best level interconnection. A fitting finale.', helpfulVotes: 35 },
    { gameIndex: 11, userIndex: 3, score: 10, body: 'Speedrunning DS3 never gets old. The movement tech and weapon variety create endless routing possibilities. The Ringed City DLC is top-tier FromSoft.', helpfulVotes: 22 },
    { gameIndex: 11, userIndex: 0, score: 8, body: 'A beautiful conclusion to the trilogy. Some areas feel a bit linear compared to DS1, but the boss quality is consistently the highest in the series.', helpfulVotes: 30 },
    // Sekiro (index 12)
    { gameIndex: 12, userIndex: 0, score: 10, body: 'The deflection system is gaming perfection. Once it clicks, every sword clash feels like a dance. Isshin Ashina is the best final boss FromSoft has ever made.', helpfulVotes: 48 },
    { gameIndex: 12, userIndex: 1, score: 9, body: 'The posture system forces aggression in a way Dark Souls never did. Genichiro on the rooftop is the gatekeeper fight that teaches you the whole game.', helpfulVotes: 38 },
    { gameIndex: 12, userIndex: 4, score: 9, body: 'Deserved every GOTY award. The grappling hook movement is exhilarating. The stealth sections in Ashina Castle make you feel like a true shinobi.', helpfulVotes: 32 },
    // Celeste (index 13)
    { gameIndex: 13, userIndex: 2, score: 10, body: 'A platformer that makes you cry. Madeline\'s journey with anxiety is told through gameplay itself — the struggle IS the story. Lena Raine\'s soundtrack is unforgettable.', helpfulVotes: 50 },
    { gameIndex: 13, userIndex: 4, score: 9, body: 'The B-sides and C-sides took hundreds of attempts each and I loved every second. Tight controls, fair difficulty, meaningful narrative. A modern classic.', helpfulVotes: 35 },
    // Stardew Valley (index 14)
    { gameIndex: 14, userIndex: 1, score: 10, body: 'Made entirely by one person and it has more content than most AAA games. The community center bundles give such a satisfying goal loop. Pure comfort gaming.', helpfulVotes: 62 },
    { gameIndex: 14, userIndex: 2, score: 9, body: 'I\'ve lost count of how many farms I\'ve started. The 1.5 update with Ginger Island added so much. ConcernedApe is the most dedicated solo dev in gaming.', helpfulVotes: 45 },
    { gameIndex: 14, userIndex: 4, score: 10, body: 'The perfect game to decompress after a long day. Fishing, farming, mining, socializing — every activity feels rewarding. Co-op with friends is a joy.', helpfulVotes: 38 },
    // Doom Eternal (index 15)
    { gameIndex: 15, userIndex: 0, score: 9, body: 'The combat loop is the greatest power fantasy in gaming. Resource management through aggression is genius design. Mick Gordon\'s soundtrack is legendary.', helpfulVotes: 42 },
    { gameIndex: 15, userIndex: 3, score: 10, body: 'Speedrunning Doom Eternal is pure chaos. The movement tech ceiling is incredibly high. Every arena is a puzzle solved with shotguns and rocket jumps.', helpfulVotes: 28 },
    // RE Village (index 16)
    { gameIndex: 16, userIndex: 2, score: 8, body: 'Lady Dimitrescu\'s castle is fantastic survival horror, but the game really shines in Heisenberg\'s factory. Each section feels like a different genre. Love the variety.', helpfulVotes: 30 },
    { gameIndex: 16, userIndex: 4, score: 7, body: 'Great atmosphere and enemy variety. The Beneviento house is genuinely terrifying. Moreau section is the weakest but doesn\'t drag the overall experience down.', helpfulVotes: 22 },
    // Monster Hunter: World (index 17)
    { gameIndex: 17, userIndex: 0, score: 9, body: 'The best onboarding MH has ever had without sacrificing depth. Iceborne expansion doubles the content and the endgame is incredibly satisfying. Hunting is addictive.', helpfulVotes: 40 },
    { gameIndex: 17, userIndex: 1, score: 10, body: 'Every weapon type is a different game entirely. I\'ve put 500+ hours in and I still haven\'t mastered the Charge Blade. The multiplayer hunts are unforgettable.', helpfulVotes: 55 },
    { gameIndex: 17, userIndex: 3, score: 8, body: 'The ecosystem design is incredible — watching a Rathalos hunt an Anjanath while you sneak past is peak emergent gameplay. Loading times could be better though.', helpfulVotes: 25 },
    // Persona 5 Royal (index 18)
    { gameIndex: 18, userIndex: 2, score: 10, body: 'Style incarnate. Every menu transition, every battle animation — everything oozes personality. The new third semester in Royal is the emotional peak of the entire series.', helpfulVotes: 55 },
    { gameIndex: 18, userIndex: 4, score: 10, body: '120+ hours and I didn\'t want it to end. The social links are deeply personal stories. Persona 5 Royal isn\'t just a JRPG — it\'s a lifestyle simulator with heart.', helpfulVotes: 48 },
    { gameIndex: 18, userIndex: 0, score: 9, body: 'The Phantom Thieves are one of gaming\'s best casts. Boss palace designs are thematically brilliant. Acid jazz soundtrack is stuck in my head permanently.', helpfulVotes: 40 },
    // Subnautica (index 19)
    { gameIndex: 19, userIndex: 1, score: 9, body: 'Terror and wonder in equal measure. Building your first Cyclops, then diving into the deep — no other game captures the fear and beauty of the ocean like this.', helpfulVotes: 42 },
    { gameIndex: 19, userIndex: 3, score: 8, body: 'The environmental storytelling is masterful. Finding PDAs from other survivors creates a narrative without cutscenes. The Leviathans are absolutely terrifying.', helpfulVotes: 30 },
    // Outer Wilds (index 20)
    { gameIndex: 20, userIndex: 0, score: 10, body: 'I would give anything to play this again for the first time. The knowledge-based progression is genius — YOU are the one who levels up, not your character.', helpfulVotes: 65 },
    { gameIndex: 20, userIndex: 2, score: 10, body: 'The moment everything clicks and you understand the big picture is the greatest revelation in gaming history. Echoes of the Eye DLC is equally stunning.', helpfulVotes: 55 },
    { gameIndex: 20, userIndex: 4, score: 9, body: 'A game that trusts the player\'s intelligence completely. No quest markers, no handholding — just pure curiosity-driven exploration. A once-in-a-generation experience.', helpfulVotes: 48 },
    // Ori WotW (index 21)
    { gameIndex: 21, userIndex: 1, score: 10, body: 'The most beautiful game ever made. Every frame is a painting. The combat is vastly improved from Blind Forest. The ending destroyed me emotionally.', helpfulVotes: 45 },
    { gameIndex: 21, userIndex: 4, score: 9, body: 'Moon Studios elevated the metroidvania genre to art. The chase sequences are heart-pounding, the exploration is rewarding, and the music is transcendent.', helpfulVotes: 38 },
    // Divinity OS2 (index 22)
    { gameIndex: 22, userIndex: 0, score: 10, body: 'The greatest CRPG ever made until Baldur\'s Gate 3. The elemental combat system creates emergent moments no scripted game can match. Co-op is chaotic brilliance.', helpfulVotes: 48 },
    { gameIndex: 22, userIndex: 2, score: 9, body: 'Fort Joy alone has more content than most RPGs. The freedom of choice is staggering — you can kill anyone, steal anything, and the game adapts. Masterpiece.', helpfulVotes: 40 },
    // Control (index 23)
    { gameIndex: 23, userIndex: 1, score: 8, body: 'The destruction physics are absurd in the best way. Ripping chunks of wall to throw at enemies never gets old. The Ashtray Maze is the single best level in gaming.', helpfulVotes: 38 },
    { gameIndex: 23, userIndex: 4, score: 7, body: 'Remedy\'s most atmospheric game. The Oldest House is a character itself. SCP vibes mixed with excellent third-person combat. The AWE DLC ties into Alan Wake perfectly.', helpfulVotes: 25 },
    // Returnal (index 24)
    { gameIndex: 24, userIndex: 0, score: 9, body: 'The DualSense haptics make every alien rain shower feel real. The bullet-hell patterns are gorgeous and terrifying. Selene\'s psychological horror story is deeply unsettling.', helpfulVotes: 35 },
    { gameIndex: 24, userIndex: 3, score: 8, body: 'The best use of roguelike structure in a AAA game. Each biome has its own identity and the weapon alt-fire system keeps combat fresh across hundreds of runs.', helpfulVotes: 28 },
    // It Takes Two (index 25)
    { gameIndex: 25, userIndex: 1, score: 9, body: 'Hazelight reinvented co-op gaming. Every chapter has completely new mechanics — magnetism, time control, size shifting. It\'s like playing 12 different games in one.', helpfulVotes: 42 },
    { gameIndex: 25, userIndex: 2, score: 10, body: 'Played this with my partner and we couldn\'t stop. The variety of gameplay mechanics per chapter is insane. Deserved GOTY 2021. A love letter to co-op gaming.', helpfulVotes: 50 },
    // Horizon Zero Dawn (index 26)
    { gameIndex: 26, userIndex: 0, score: 9, body: 'Aloy is one of gaming\'s best protagonists. The mystery of what happened to the old world kept me hooked. Hunting Thunderjaws with tearblast arrows is peak satisfaction.', helpfulVotes: 38 },
    { gameIndex: 26, userIndex: 4, score: 8, body: 'The machine combat is what sets it apart. Stripping armor plates and targeting weak points is strategic and thrilling. The photo mode is gorgeous too.', helpfulVotes: 28 },
    // Terraria (index 27)
    { gameIndex: 27, userIndex: 1, score: 10, body: 'The most content-rich game in existence. Re-Logic kept adding free updates for over a decade. Every boss, every biome, every item is a labor of love.', helpfulVotes: 58 },
    { gameIndex: 27, userIndex: 3, score: 9, body: 'Expert mode + Master mode is the ultimate challenge. Building elaborate arenas for each boss fight is half the fun. The progression system is deeply satisfying.', helpfulVotes: 35 },
    // Valheim (index 28)
    { gameIndex: 28, userIndex: 0, score: 8, body: 'Building a Viking longhouse with friends at sunset, then sailing into the unknown — Valheim creates moments no scripted game can match. Lo-fi beauty at its finest.', helpfulVotes: 32 },
    { gameIndex: 28, userIndex: 2, score: 7, body: 'The combat needs polish but the exploration and building are addictive. Swamp biome is genuinely terrifying. Best played with a group of friends on a dedicated server.', helpfulVotes: 20 },
    // Half-Life: Alyx (index 29)
    { gameIndex: 29, userIndex: 0, score: 10, body: 'The best VR game ever made, and it\'s not close. Valve proved VR isn\'t a gimmick — it\'s the future. The Jeff chapter is the most tense hour I\'ve ever experienced in gaming.', helpfulVotes: 60 },
    { gameIndex: 29, userIndex: 4, score: 10, body: 'The ending recontextualizes the entire Half-Life series. Gravity Gloves are the most natural-feeling VR interaction ever designed. This is what we waited 16 years for.', helpfulVotes: 55 },
    // Slay the Spire (index 30)
    { gameIndex: 30, userIndex: 1, score: 10, body: 'The game that created an entire genre. Every card, every relic, every event is perfectly balanced. 500+ hours and I\'m still discovering new synergies. The Watcher is perfection.', helpfulVotes: 48 },
    { gameIndex: 30, userIndex: 3, score: 9, body: 'Ascension 20 Heart kills are the ultimate deckbuilding challenge. The community modding scene keeps it fresh forever. No other deckbuilder compares.', helpfulVotes: 35 },
    // The Last of Us Part I (index 31)
    { gameIndex: 31, userIndex: 2, score: 9, body: 'The PS5 remake is stunning. The facial animations during emotional scenes hit differently with the new tech. Joel and Ellie\'s journey remains gaming\'s best story.', helpfulVotes: 40 },
    { gameIndex: 31, userIndex: 4, score: 8, body: 'The most cinematic game ever made. Every encounter is tense, every quiet moment is earned. The Left Behind DLC is essential. A masterclass in pacing.', helpfulVotes: 32 },
    // Cuphead (index 32)
    { gameIndex: 32, userIndex: 0, score: 9, body: 'Every frame is a work of art. The hand-drawn animation is labor of love visible in every boss design. King Dice\'s gauntlet is the ultimate skill check.', helpfulVotes: 38 },
    { gameIndex: 32, userIndex: 3, score: 10, body: 'Speedrunning Cuphead is insane. Every boss has perfect patterns to learn. The DLC Delicious Last Course adds some of the best bosses in the entire game.', helpfulVotes: 25 },
    // Titanfall 2 (index 33)
    { gameIndex: 33, userIndex: 1, score: 10, body: 'Effect and Cause is the best single level in FPS history. The bond with BT-7274 made me emotional about a robot. Criminally underrated due to terrible release timing.', helpfulVotes: 55 },
    { gameIndex: 33, userIndex: 0, score: 9, body: 'The movement system ruins every other FPS for you. Wall-running, sliding, and grappling at maximum speed is pure joy. Protocol 3: Protect the Pilot. 😢', helpfulVotes: 45 },
    // Deep Rock Galactic (index 34)
    { gameIndex: 34, userIndex: 1, score: 10, body: 'ROCK AND STONE! The best co-op game ever made. Every dwarf class is essential, every cave is unique. Ghost Ship Games listens to their community like no other studio.', helpfulVotes: 50 },
    { gameIndex: 34, userIndex: 3, score: 9, body: 'If you don\'t Rock and Stone, you ain\'t comin\' home! The procedural cave generation is incredible. Custom loadouts and active perks add so much depth to each class.', helpfulVotes: 40 },
    // Shovel Knight (index 35)
    { gameIndex: 35, userIndex: 2, score: 8, body: 'Three full campaigns plus Showdown, all for one price. The original campaign is a perfect NES-era homage. King Knight\'s campaign is surprisingly deep.', helpfulVotes: 25 },
    { gameIndex: 35, userIndex: 4, score: 9, body: 'Yacht Club proved retro doesn\'t mean simple. The level design is incredibly tight and every sub-weapon changes your approach. Specter Knight\'s campaign is the GOAT.', helpfulVotes: 30 },
    // Factorio (index 36)
    { gameIndex: 36, userIndex: 0, score: 10, body: 'Warning: this game will consume your life. The factory must grow. Optimizing throughput ratios at 3 AM is somehow the most fun I\'ve had gaming. Overwhelmingly Positive on Steam for a reason.', helpfulVotes: 55 },
    { gameIndex: 36, userIndex: 1, score: 9, body: 'The mod community has effectively tripled the game\'s content. Space Exploration mod alone adds 500+ hours. The 1.1 update polish shows Wube\'s commitment to quality.', helpfulVotes: 42 },
    // Neon White (index 37)
    { gameIndex: 37, userIndex: 3, score: 10, body: 'The ultimate speedrun game. Finding shortcuts and shaving milliseconds off each level is incredibly addicting. The card-weapon system is genius design.', helpfulVotes: 35 },
    { gameIndex: 37, userIndex: 4, score: 8, body: 'The anime visual novel sections won\'t be for everyone, but the gameplay is some of the tightest FPS platforming ever made. Getting all ace medals is a thrill.', helpfulVotes: 22 },
    // RE4 Remake (index 38)
    { gameIndex: 38, userIndex: 0, score: 10, body: 'Capcom remade the GOAT and somehow made it better. The village siege is even more intense. The knife parry system adds a whole new skill dimension. Leon is iconic.', helpfulVotes: 52 },
    { gameIndex: 38, userIndex: 2, score: 9, body: 'Every area has been reimagined beautifully. The Regenerador encounter in the lab is pure terror with the RE Engine\'s graphics. Separate Ways DLC is essential.', helpfulVotes: 40 },
    { gameIndex: 38, userIndex: 1, score: 9, body: 'The merchant\'s expanded role and personality add so much charm. Weapon upgrading feels even more satisfying. "What are ya buyin?" hits different in 2023.', helpfulVotes: 35 },
    // Undertale (index 39)
    { gameIndex: 39, userIndex: 2, score: 10, body: 'Toby Fox made genocide runs make YOU feel guilty. Your choices genuinely haunt you across save files. The soundtrack — Megalovania, Hopes and Dreams — is all-time great.', helpfulVotes: 55 },
    { gameIndex: 39, userIndex: 4, score: 9, body: 'A revolution in RPG design. The MERCY system forces you to think about what kind of player you are. Sans\' judgment at the end of pacifist hits like a truck.', helpfulVotes: 42 },
    // Portal 2 (index 40)
    { gameIndex: 40, userIndex: 0, score: 10, body: 'Cave Johnson\'s lemon rant is the funniest moment in gaming. The co-op puzzles with Atlas and P-body are brilliantly designed. Valve at their creative peak.', helpfulVotes: 60 },
    { gameIndex: 40, userIndex: 1, score: 10, body: 'Wheatley\'s character arc is a masterclass in comedy writing. The old Aperture labs section reveals incredible lore. This game has no flaws. None.', helpfulVotes: 55 },
    { gameIndex: 40, userIndex: 4, score: 9, body: 'The gel mechanics add so much variety to the puzzle design. The ending is genuinely emotional. The community workshop extends it infinitely. True perfection.', helpfulVotes: 45 },
    // RimWorld (index 41)
    { gameIndex: 41, userIndex: 0, score: 9, body: 'The stories this game generates are better than most written narratives. My colony survived toxic fallout, a manhunting pack, and a siege — then the cook had a mental break and burned it all down.', helpfulVotes: 50 },
    { gameIndex: 41, userIndex: 2, score: 8, body: 'The modding community is the best in gaming. Vanilla is great, but with 200 mods it becomes the most detailed colony sim ever created. Cassandra Classic is life.', helpfulVotes: 35 },
    // Bloodborne (index 42)
    { gameIndex: 42, userIndex: 0, score: 10, body: 'The greatest atmosphere in gaming. Yharnam at night, the blood moon rising, the cosmic horror reveal — nothing compares. The Old Hunters DLC is FromSoft\'s best work.', helpfulVotes: 62 },
    { gameIndex: 42, userIndex: 3, score: 10, body: 'The rally mechanic is genius — it rewards aggression instead of hiding behind a shield. Ludwig the Accursed is the best boss in gaming history. Please give us a PC port.', helpfulVotes: 55 },
    { gameIndex: 42, userIndex: 1, score: 9, body: 'From Central Yharnam to the Nightmare of Mensis, every area tells a story through its design. The trick weapons are the most creative combat system FromSoft has ever made.', helpfulVotes: 45 },
    // Prey (index 43)
    { gameIndex: 43, userIndex: 2, score: 9, body: 'The most underrated game of its generation. Talos I is one of the best-crafted game environments ever made. The Typhon powers allow incredible creativity in problem-solving.', helpfulVotes: 38 },
    { gameIndex: 43, userIndex: 4, score: 8, body: 'Arkane\'s immersive sim design at its peak alongside Dishonored. Mimics make you paranoid about every coffee cup. The Mooncrash DLC is a roguelike masterclass.', helpfulVotes: 28 },
    // Inscryption (index 44)
    { gameIndex: 44, userIndex: 0, score: 9, body: 'The less I say, the better. This game is three games in a trenchcoat pretending to be one game, and somehow it works. Daniel Mullins is a mad genius.', helpfulVotes: 42 },
    { gameIndex: 44, userIndex: 1, score: 10, body: 'My jaw hit the floor multiple times. The way it subverts your expectations is unmatched. The cabin card game segment alone is worth the price of admission.', helpfulVotes: 50 },
    // Hitman 3 (index 45)
    { gameIndex: 45, userIndex: 0, score: 8, body: 'Dartmoor murder mystery is the best sandboxlevel IO has ever made. Playing detective as Agent 47 in disguise is endlessly entertaining. The escalation contracts add huge replay value.', helpfulVotes: 32 },
    { gameIndex: 45, userIndex: 2, score: 9, body: 'Berlin\'s reversed premise — where YOU are the target — is brilliant. Having all three games accessible from one launcher creates the ultimate assassination sandbox.', helpfulVotes: 38 },
    // Tunic (index 46)
    { gameIndex: 46, userIndex: 4, score: 9, body: 'Looks like a cute Zelda clone until you start deciphering the in-game manual. The late-game revelations are on par with Fez and Outer Wilds. Do NOT look up guides.', helpfulVotes: 35 },
    { gameIndex: 46, userIndex: 1, score: 8, body: 'Andrew Shouldice created something special. The fox is adorable but the game hides genuine challenge and deep puzzles beneath its cute exterior. The Holy Cross is mind-blowing.', helpfulVotes: 28 },
    // Death Stranding (index 47)
    { gameIndex: 47, userIndex: 2, score: 8, body: 'It IS a walking simulator and it\'s somehow captivating. The strand system — seeing other players\' structures — makes you feel connected. Kojima\'s most personal game.', helpfulVotes: 30 },
    { gameIndex: 47, userIndex: 0, score: 7, body: 'Not for everyone, but those who connect with it REALLY connect. The zip-line network you build in the mountains is incredibly satisfying. The star-studded cast delivers.', helpfulVotes: 22 },
    // Psychonauts 2 (index 48)
    { gameIndex: 48, userIndex: 1, score: 9, body: 'Tim Schafer hasn\'t lost his touch. The mental world designs are wildly creative — a psychedelic rock concert, a cooking show, a hospital of senses. The writing is laugh-out-loud funny.', helpfulVotes: 35 },
    { gameIndex: 48, userIndex: 4, score: 8, body: 'The most inventive platformer level design since Mario Galaxy. Each mind is a visual feast. The handling of mental health themes is respectful and touching.', helpfulVotes: 25 },
    // Sifu (index 49)
    { gameIndex: 49, userIndex: 3, score: 9, body: 'Finishing the game without aging past 25 is the ultimate flex. The hand-to-hand combat is the best in gaming — every punch has weight. Sloclap nailed the kung-fu fantasy.', helpfulVotes: 38 },
    { gameIndex: 49, userIndex: 0, score: 8, body: 'The aging mechanic is genius — it creates natural difficulty curves. Museum level is visually stunning. The post-launch updates added arenas and difficulty options. Great value.', helpfulVotes: 28 },
  ];

  for (const rev of reviewsData) {
    await prisma.review.create({
      data: {
        score: rev.score,
        body: rev.body,
        helpfulVotes: rev.helpfulVotes,
        gameId: games[rev.gameIndex].id,
        userId: users[rev.userIndex].id,
      },
    });
  }

  console.log(`✅ Created ${reviewsData.length} reviews`);
  console.log('🎮 Seeding complete!');
}

main()
  .catch((e) => {
    console.error('❌ Seed error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
